/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tv.sonis.lobber;

import com.sun.jna.platform.WindowUtils;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tv.sonis.*;
import tv.sonis.lobber.graphics.LobberCanvas;
import tv.sonis.lobber.model.TransparentFrame;

/**
 *
 * @author skaviouz
 */
public class AboutDialogBox extends javax.swing.JDialog {

    public LobberToolApplication LTA = null;

    /**
     * Creates new form AboutDialogueBox
     */
    public AboutDialogBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        LTA = (LobberToolApplication) parent;
        initComponents();
        tabulateContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new ColorJTextPane(){{
            append(Color.black, "\nRight click to hide/unhide this dialogue box!");
            append(Color.red,   "\nPlease Read this tutorial carefully!");
            append(Color.black, "\n");
            append(Color.black, "\nThe format for values:");
            append(Color.black, "\neach plot gets a newline");
            append(Color.black, "\nExamples of good / bad : ");
            append(Color.blue, "\nAzimuth//RED,GREEN,BLUE,ALPHA//THICKNESS//NOTE");
            append(Color.blue, "\nAzimuth can be whole or decimal.");
            append(Color.blue, "\n    \"1.\" translates to \"1.0\"");
            append(Color.blue, "\n    Azimuth modulus (%) 360");
            append(Color.blue, "\nSeperator always is //");
            append(Color.blue, "\n    skipping values use default ones");
            append(Color.blue, "\nRED,GREEN,BLUE,ALPHA rep by 0-255 each value");
            append(Color.blue, "\n    you can leave numbers out");
            append(Color.blue, "\nThickness");
            append(Color.blue, "\n    in degrees, min. is 0.1° default is 1°");
            append(Color.blue, "\n");
            append(Color.blue, "\nExamples: ");
            append(Color.green, "(GREEN IS GOOD)");
            append(Color.red, "(RED IS BAD)");
            append(Color.black, "\n");
            append(Color.green, "\n222//255//22//NOTE          ");
            append(Color.black, "\n     ");
            append(Color.black, "> 222.0//255,0,0,40//22.0//NOTE");
            append(Color.green, "\n222                         ");
            append(Color.black, "\n     ");
            append(Color.black, "> 222.0//0,0,0,40//1.0");
            append(Color.green, "\n222.0////0.1                ");
            append(Color.black, "\n     ");
            append(Color.black, "> 222.0//0,0,0,40//0.1");
            append(Color.green, "\n222.0//,,255,30//2          ");
            append(Color.black, "\n     ");
            append(Color.black, "> 222.0//0,0,255,30//2.0");
            append(Color.green, "\n222.0//,255//3.             ");
            append(Color.black, "\n     ");
            append(Color.black, "> 222.0//0,255,0,40//3.0");
            append(Color.red, "\n222.0,//255,0,0,80,//22.0,//2");
            append(Color.black, "\n     ");
            append(Color.black, "> tokenizer doesn't check azi/thickness");
            append(Color.black, "\n     ");
            append(Color.black, "> Ignore line if uncorrectable error found!");

        }};
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new ColorJTextPane(){{
            append(Color.black, "\n");
            append(Color.black, "\nv 5.0   -   Code:       Added improvements, mostly gui fixes, using github for revision control");
            append(Color.black, "\nv 4.2.5-b67 Code:       Testing gui improvements, added helpers");
            append(Color.black, "\nv 4.2   -   Code:       Noted out algebra, less boilerplate (85% less)");
            append(Color.blue, "\n                NOTE: trigonometry uses 5 lines vs. algebra version used 40+");
            append(Color.blue, "\n                NOTE: algebra left for historic data");
            append(Color.green, "\n                TODO: will remove in couple git updates");
            append(Color.black, "\nv 4.1   -   VERSION:    version update, adjustments");
            append(Color.blue, "\n                NOTE: Version info was wrong, small gui adjustments");
            append(Color.black, "\nv 4.0   -   Code:       less boilerplate, took out proprietary graphics library");
            append(Color.blue, "\n                NOTE: Took out geosoft.no graphics library");
            append(Color.black, "\nv 3.5   -   GUI:       bug fixes");
            append(Color.blue, "\n                NOTE: broken keybindings, autosize adjustments removed for now");
            append(Color.black, "\nv 3.0   -   GUI:        included adjustable settings");
            append(Color.blue, "\n                NOTE: request for adjustable settings");
            append(Color.black, "\nv 2.0   -   ADD:        included other features like wifi calculator");
            append(Color.blue, "\n                NOTE: programmed other features I thought would be useful");
            append(Color.black, "\nv 1.5   -   Code:       fixed algorithm bug");
            append(Color.blue, "\n                NOTE: 135-225° was reversed like 225-135° (flipped)");
            append(Color.black, "\nv 1.0   -   Code:       basic instructions written");
            append(Color.blue, "\n                NOTE:   algebra, geosoft.no/graphics/, swing");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");

        }};
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        values = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldAzimuth = new javax.swing.JTextField();
        jComboBox1LineColor = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox1LabelTheID = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jTextField2Alpha = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField3ArcThickness = new javax.swing.JTextField();
        jButton1Add = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSlider4 = new javax.swing.JSlider();
        jLabel28 = new javax.swing.JLabel();
        jSlider5 = new javax.swing.JSlider();
        jLabel29 = new javax.swing.JLabel();
        jSlider6 = new javax.swing.JSlider();
        jLabel30 = new javax.swing.JLabel();
        jSlider7 = new javax.swing.JSlider();

        setModalExclusionType(null);
        setModalityType(null);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lobber Tools - \"Graph like a pro!\"");

        jLabel2.setText("Version");

        jLabel3.setText("v5.0");

        jLabel4.setText("Programmer");

        jLabel5.setText("Eric M. Horvitz II");

        jLabel6.setText("From the insirpration of");

        jLabel7.setText("Tom Waller");

        jLabel8.setText("James Bennet");

        jLabel9.setText("Basis");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This program takes azmuth inputs and outputs graphical representations of said azmuths.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setText("Honorably Mentioned");

        jLabel20.setText("Stephen Gilmore");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("About", jPanel1);

        jTextPane1.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("How", jPanel3);

        jTextPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPane2formMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTextPane2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Version", jPanel7);

        values.setColumns(20);
        values.setRows(5);
        values.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                valuesMouseClicked(evt);
            }
        });
        values.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valuesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valuesKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(values);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Azmuth Autofill", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel22.setText("Azimuth");

        jTextFieldAzimuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAzimuthActionPerformed(evt);
            }
        });

        jComboBox1LineColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yellow", "Red" }));

        jLabel23.setText("Line Color");

        jLabel24.setText("LabelID");

        jTextField2Alpha.setText("40");
        jTextField2Alpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2AlphaActionPerformed(evt);
            }
        });

        jLabel25.setText("Alpha");

        jLabel26.setText("Arc/Thickness");

        jTextField3ArcThickness.setText("1.00");
        jTextField3ArcThickness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ArcThicknessActionPerformed(evt);
            }
        });

        jButton1Add.setText("Add");
        jButton1Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AddActionPerformed(evt);
            }
        });

        jLabel27.setText("Paste");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAzimuth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jComboBox1LineColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2Alpha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1LabelTheID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3ArcThickness))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1Add)
                    .addComponent(jLabel27))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAzimuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1LineColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2Alpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jCheckBox1LabelTheID))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3ArcThickness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1Add)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Values", jPanel4);

        jSlider1.setMaximum(3600);
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jSlider2.setMaximum(3600);
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });

        jSlider3.setMaximum(3600);
        jSlider3.setValue(0);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });

        jButton1.setText("Load Background from clipboard");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("White background");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSlider4.setMaximum(2000);
        jSlider4.setValue(1000);
        jSlider4.setEnabled(false);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });

        jLabel28.setText("Adjust line position / location (top is horizontal/x) [disabled]");
        jLabel28.setEnabled(false);

        jSlider5.setMaximum(2000);
        jSlider5.setValue(1000);
        jSlider5.setEnabled(false);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });

        jLabel29.setText("Transparency");

        jSlider6.setValue(100);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });

        jLabel30.setText("OFFSET");

        jSlider7.setMaximum(3600);
        jSlider7.setValue(0);
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider7StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(jSlider7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ref", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == 3) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_formMouseClicked

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        LobberCanvas.bar[0] = jSlider1.getValue() / 10.00;
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        LobberCanvas.bar[1] = jSlider2.getValue() / 10.00;
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        LobberCanvas.bar[2] = jSlider3.getValue() / 10.00;
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider3StateChanged
    public int up = 0;

    public int up() {
        up++;
        return up;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        try {
            ((LobberCanvas)LTA.canvas2).image = (BufferedImage) clipboard.getData(DataFlavor.imageFlavor);
        } catch (UnsupportedFlavorException | IOException ex) {
            Logger.getLogger(AboutDialogBox.class.getName()).log(Level.SEVERE, null, ex);
        }
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((LobberCanvas)LTA.canvas2).image = null;
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        LobberCanvas.bar[3] = jSlider4.getValue();
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
        LobberCanvas.bar[4] = jSlider5.getValue();
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider5StateChanged

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6StateChanged
            if(!jSlider6.getValueIsAdjusting()){
               WindowUtils.setWindowAlpha(LTA, jSlider6.getValue()/100f);
            }
    }//GEN-LAST:event_jSlider6StateChanged

    private void jSlider7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider7StateChanged
        LobberCanvas.bar[5] = jSlider7.getValue();
        LTA.canvas2.repaint();
    }//GEN-LAST:event_jSlider7StateChanged

    private void jTextPane2formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane2formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane2formMouseClicked

    private void jButton1AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AddActionPerformed
        jTextFieldAzimuthActionPerformed(null);
    }//GEN-LAST:event_jButton1AddActionPerformed

    private void jTextField3ArcThicknessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ArcThicknessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ArcThicknessActionPerformed

    private void jTextField2AlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2AlphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2AlphaActionPerformed

    private void jTextFieldAzimuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAzimuthActionPerformed
        try {
            //check values
            double azi = Double.parseDouble(jTextFieldAzimuth.getText());
            int color = jComboBox1LineColor.getSelectedIndex();//0=yellow, 1=red
            int alpha = Integer.parseInt(jTextField2Alpha.getText());
            boolean label = jCheckBox1LabelTheID.isSelected();
            double arc = Double.parseDouble(jTextField3ArcThickness.getText());
            //values good

            //check ___
            String colors = (color == 0) ? "255,255,0" : (color == 1) ? "255,0,0" : (color == 2) ? "" : (color == 3) ? "" : (color == 4) ? "" : (color == 5) ? "" : "";
            if (alpha != -1 && alpha != 0 && alpha < 255) {
                colors = colors + "," + alpha;
            }
            String labels = "";
            if (label) {
                labels = "//" + up();
            }
            values.append(azi + "//" + colors + "//" + arc + labels + "\n");
            /*
            * EXAMPLE: * 255//255,255,0,25//240 25//255,255,0,25//45
            * 180//255,0,0,25//33 145//0,0,255,25//22 //___ are/is good
            *
            *
            */

            //values are good, added to values box, reset easy field...
            jTextFieldAzimuth.setText("");
            valuesKeyPressed(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldAzimuthActionPerformed

    private void valuesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valuesKeyPressed
        ((LobberCanvas) LTA.canvas2).setValids(values.getText().split("\n"));
    }//GEN-LAST:event_valuesKeyPressed

    private void valuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valuesMouseClicked
        if (evt.getButton() == 3) {
            this.setVisible(false);
            valuesKeyPressed(null);
        }
    }//GEN-LAST:event_valuesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Add;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1LabelTheID;
    private javax.swing.JComboBox jComboBox1LineColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    public javax.swing.JSlider jSlider4;
    public javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2Alpha;
    private javax.swing.JTextField jTextField3ArcThickness;
    private javax.swing.JTextField jTextFieldAzimuth;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextArea values;
    // End of variables declaration//GEN-END:variables

    private void tabulateContent() {
//        String s = "This program is version 4";
//        AboutText.setText(s);
        //jTextArea1.setText(null);
    }

    private void addAboutText(String s) {
        //String old = AboutText.get
    }
}
