/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tv.sonis.lobber;

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import tv.sonis.lobber.graphics.LobCanvas;
import tv.sonis.lobber.util.lobberstatics;

/**
 *
 * @author skaviouz
 */
public class LobberApplication extends JFrame {

    public MainPane mainPane;

    public LobberApplication() {
        //self awareness =D
        if (lobberstatics.lobapp == null) {
            lobberstatics.lobapp = this;
        }
        initComponents();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LobberApplication().setVisible(true);
            }
        });
    }

    private void initComponents() {
        mainPane = new MainPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        add(mainPane, java.awt.BorderLayout.CENTER);
        setSize(800, 600);
        setTitle("what's up");

        final List<Image> icons;
        icons = new ArrayList<Image>();
        try {
            URL url16 = new URL("http://i.stack.imgur.com/m0KKu.png");
            URL url32 = new URL("http://i.stack.imgur.com/LVVMb.png");

            //icons.add(ImageIO.read(new File("favicon.ico")));
            BufferedImage bfi = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2dbfi;
            setIconImage(new BufferedImage(16, 16, 3));
            //icons.add(ImageIO.read(url32));
        } catch (IOException ex) {
            Logger.getLogger(LobberApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
        setIconImages(icons);
        setLocationByPlatform(true);
        //setIconImage(new ImageIcon("C:/aProject/lobber/favicon.ico").getImage());

        //pack();
    }

    public class MainPane extends JPanel {

        private Graphics2D g2d;
        private String state = "";
        private int x, y;

        public MainPane() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        private void initComponents() {

            LobCanvas t = new LobCanvas();
            t.setVisible(true);
            //this will fail if mainpane isn't through lobapp
            add(t, java.awt.BorderLayout.CENTER);
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            g2d = (Graphics2D) g;

            g2d.setColor(new Color(0, 0, 0, 90));
            g2d.drawString("\u00a9" + " Skaviouz 2009", getWidth() - 95, getHeight() - 10);
            if (!state.equals("")) {
                g2d.drawString("STATE: " + state, 5, 25);
            }

            g2d.dispose();
        }

        public void setState(String state) {
            this.state = state;
        }

        public String getState() {
            return state;
        }

        public void setX(int x) {
            this.x = x;
            repaint();
        }

        public void setY(int y) {
            this.y = y;
            repaint();
        }
    }
}
