/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tv.sonis.lobber;

import java.awt.Button;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JTabbedPane;
import tv.sonis.lobber.util.Constants;
import tv.sonis.lobber.util.lobberstatics;

/**
 * Default application JFrame Example how to use Canvas
 *
 * @author skaviouz
 */
public class LobberApplication extends JFrame {

    public MainPane mainPane;

    public LobberApplication() {
        //self awareness =D
        if (lobberstatics.lobapp == null) {
            lobberstatics.lobapp = this;
        }
        initComponents();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LobberApplication().setVisible(true);
            }
        });
    }

    private void initComponents() {
        mainPane = new MainPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        add(mainPane);
        setSize(800, 600);
        setTitle(Constants.getTitle());
        ImageIcon II = new ImageIcon("./resources/images/icon32_S.png");
        setIconImage(II.getImage());
        setLocationByPlatform(true);
    }

    public class MainPane extends JPanel implements MouseListener, MouseMotionListener {

        private Graphics2D g2d;
        private String state = "";
        private int x, y;
        public boolean ViewGraph = true;
        public JTabbedPane MainTab = new JTabbedPane();
        public JPanel About, How, Version, Values, Ref;

        public MainPane() {
            super(new GridBagLayout(), true);
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        private void initComponents() {
            addMouseMotionListener(this);
            addMouseListener(this);
            MainTab.add("asdfasdf", new JPanel());
            setVisible(true);
        }

        //@Override
        public void paintComponent(Graphics g) {
            if (ViewGraph) {
                super.paintComponent(g);
                return;
            }
            g2d = (Graphics2D) g;

            int y = getHeight();
            int x = getWidth();

            Graphics2D g2d = (Graphics2D) g.create();
            LobberGraphics:
            {
                Shape cirzzz;
                //cirzzz = Ellipse2D.Double(x/2, y/2, 60, 120);
                g2d.setColor(Color.red);
                g2d.drawOval(x / 2, y / 2, 40, 60);
            }
            testString:
            {
                g2d.setColor(Color.red);
                g2d.drawString("Hello", 50, 50);
            }
            box:
            {
                g2d.setColor(Color.red);
                Rectangle2D r2d = new Rectangle2D.Double(15, 5, x - 25, y - 25);
                g2d.draw(r2d);
            }
            copyrigbht:
            {
                g2d.setColor(new Color(0, 0, 0, 90));
                g2d.drawRect(x - 96, y - 21, 93, 12);
                g2d.drawString("\u00a9" + " Skaviouz 2009", x - 95, y - 10);
                if (!state.equals("")) {
                    g2d.drawString("STATE: " + state, 5, 25);
                }
            }

            g2d.dispose();
        }

        public void setState(String state) {
            this.state = state;
        }

        public String getState() {
            return state;
        }

        public void setX(int x) {
            this.x = x;
            repaint();
        }

        public void setY(int y) {
            this.y = y;
            repaint();
        }

        //MouseMotionListener
        /*
         * M/C + M MOVE
         */
        @Override
        public void mouseDragged(MouseEvent e) {
        }

        /*
         * M MOVE
         */
        @Override
        public void mouseMoved(MouseEvent e) {
        }

        //MouseListener
        @Override
        public void mouseClicked(MouseEvent e) {
        }

        @Override
        public void mousePressed(MouseEvent e) {
        }

        @Override
        public void mouseReleased(MouseEvent e) {
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
    }
}
