/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tv.sonis.lobber;

import java.awt.Color;
import tv.sonis.*;

/**
 * TODO: fix circle on representation
 * 
 * @author skaviouz
 */
public class LobberDialogBox extends javax.swing.JDialog {

    public LobberToolApplication LTA = null;
    /**
     * Creates new form LobberDialogBox
     */
    public LobberDialogBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        LTA = (LobberToolApplication) parent;
        initComponents();
        tabulateContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanelHow = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new ColorJTextPane(){{
            append(Color.black, "LOBBER TOOLS LICENSE AGREEMENT"
                + "\n\nTHIS AGREEMENT is entered into as of Dec. 17th, 2012(\"Effective Date\") by and between Eric M. Horvitz <http://sonis.tv/> with an email-address eric.horvitz@sonis.tv (\"LICENSOR\") and Tom Waller (\"LICENSEE\")."
                + "\n\nWHEREAS, Licensee wishes to license software and Licensor desires to license this software to licensee."
                + "\n\nNOW THEREFORE, the parties hereto agree as follows:"
                + "\n\n1. GRANT OF LICENSE");
            append(Color.red,   "\nPlease Read this tutorial carefully!");
            append(Color.black, "\n");
            append(Color.black, "\nAbout: Programmer notes");
            append(Color.black, "\nHow: This Guide");
            append(Color.black, "\nHistory: brief program history");
            append(Color.black, "\nValues: This is where you input the values of azimuths.");
            append(Color.black, "\n   you can use the built in add'r to learn the format.");
            append(Color.black, "\n   you can also copy and paste 'human' code.");
            append(Color.black, "\nRef: used to make reference azimuths.");
            append(Color.black, "\nOPI: Options.");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");

        }};
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new ColorJTextPane(){{
            append(Color.black, "\nRight click to hide/unhide this dialogue box!");
            append(Color.red,   "\nPlease Read this tutorial carefully!");
            append(Color.black, "\n");
            append(Color.black, "\nAbout: Programmer notes");
            append(Color.black, "\nHow: This Guide");
            append(Color.black, "\nHistory: brief program history");
            append(Color.black, "\nValues: This is where you input the values of azimuths.");
            append(Color.black, "\n   you can use the built in add'r to learn the format.");
            append(Color.black, "\n   you can also copy and paste 'human' code.");
            append(Color.black, "\nRef: used to make reference azimuths.");
            append(Color.black, "\nOPI: Options.");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");
            append(Color.black, "\n");

        }};

        setTitle("Lobber Tools \"Officers like pretty colors\"");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(null);
        setModalityType(null);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LobberMouseClick(evt);
            }
        });

        jPanelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAboutformMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lobber Tools - \"Graph like a pro!\"");

        jLabel2.setText("Version");

        jLabel3.setText("v4.2.5-b67");

        jLabel4.setText("Programmer");

        jLabel5.setText("Eric M. Horvitz II");

        jLabel6.setText("From the insirpration of");

        jLabel7.setText("Tom Waller");

        jLabel8.setText("James Bennet");

        jLabel9.setText("Basis");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This program takes azmuth inputs and outputs graphical representations of said azmuths.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel10.setText("Honorably Mentioned");

        jLabel20.setText("Stephen Gilmore");

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAboutLayout.createSequentialGroup()
                        .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                        .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)))
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabbedPane1.addTab("About", jPanelAbout);

        jTextPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPane1formMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanelHowLayout = new javax.swing.GroupLayout(jPanelHow);
        jPanelHow.setLayout(jPanelHowLayout);
        jPanelHowLayout.setHorizontalGroup(
            jPanelHowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
            .addGroup(jPanelHowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE))
        );
        jPanelHowLayout.setVerticalGroup(
            jPanelHowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(jPanelHowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
        );

        TabbedPane1.addTab("License", jPanelHow);

        jTextPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPane2formMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextPane2);

        TabbedPane1.addTab("How", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LobberMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LobberMouseClick
        // TODO add your handling code here:
    }//GEN-LAST:event_LobberMouseClick

    private void jPanelAboutformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAboutformMouseClicked
        if (evt.getButton() == 3) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jPanelAboutformMouseClicked

    private void jTextPane1formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane1formMouseClicked
        if (evt.getButton() == 3) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTextPane1formMouseClicked

    private void jTextPane2formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPane2formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPane2formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LobberDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LobberDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LobberDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LobberDialogBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LobberDialogBox dialog = new LobberDialogBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelHow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

    private void tabulateContent() {
    }
}
